version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app
    # muda a porta no HOST para 5433 (internamente segue 5432)
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d app"]
      interval: 5s
      timeout: 3s
      retries: 20

  redis:
    image: redis:7
    # muda a porta no HOST para 6380 (internamente segue 6379)
    ports:
      - "6380:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20

  backend:
    build: ./ecommerce-api
    env_file:
      - ./ecommerce-api/.env.docker
    # aplica as migrações e inicia a API já compilada
    command: sh -c "npx prisma migrate deploy && node dist/main.js"
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    build: ./frontend
    env_file:
      - ./frontend/.env.docker
    command: sh -c "npm run dev -- --host"
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  db-data:
